import { create } from 'zustand';

const INITIAL_CONTRACTS = [
  // SHELF: CONVICTION
  {
    id: "spx-7620-c",
    ticker: "SPX",
    strike: 7620,
    isCall: true,
    health: 96,
    expectedMove: "+42.5%",
    action: "ENTER" as const,
    narrative:
      "Heavy institutional volume cluster matched. Dealer buy walls are perfectly positioned.",
    tagText: "CONVICTION",
    shelf: "conviction",
    delta: 0.54,
    gamma: 0.024,
    vega: 0.14,
    theta: -0.81,
    volume: 14205,
    price: 5.4,
    bid: 5.35,
    ask: 5.45,
    t1: 7.2,
    p1: 33,
  },
  {
    id: "spy-515-c",
    ticker: "SPY",
    strike: 515,
    isCall: true,
    health: 93,
    expectedMove: "+36.2%",
    action: "ENTER" as const,
    narrative: "Unusually clean volume profile confirms call momentum.",
    tagText: "CONVICTION",
    shelf: "conviction",
    delta: 0.48,
    gamma: 0.038,
    vega: 0.12,
    theta: -0.45,
    volume: 38201,
    price: 3.2,
    bid: 3.18,
    ask: 3.22,
    t1: 4.35,
    p1: 36,
  },
  {
    id: "qqq-448-c",
    ticker: "QQQ",
    strike: 448,
    isCall: true,
    health: 91,
    expectedMove: "+29.0%",
    action: "ENTER" as const,
    narrative: "Dealer block purchases confirm near-term floor.",
    tagText: "CONVICTION",
    shelf: "conviction",
    delta: 0.52,
    gamma: 0.041,
    vega: 0.15,
    theta: -0.55,
    volume: 22401,
    price: 4.2,
    bid: 4.15,
    ask: 4.25,
    t1: 5.4,
    p1: 29,
  },
  {
    id: "ndx-18350-c",
    ticker: "NDX",
    strike: 18350,
    isCall: true,
    health: 90,
    expectedMove: "+31.4%",
    action: "ENTER" as const,
    narrative: "Rapid acceleration in derivative order flow on Nasdaq nodes.",
    tagText: "CONVICTION",
    shelf: "conviction",
    delta: 0.49,
    gamma: 0.015,
    vega: 0.18,
    theta: -1.25,
    volume: 5204,
    price: 15.5,
    bid: 15.3,
    ask: 15.7,
    t1: 20.3,
    p1: 31,
  },
  {
    id: "spx-7600-c",
    ticker: "SPX",
    strike: 7600,
    isCall: true,
    health: 95,
    expectedMove: "+39.1%",
    action: "ENTER" as const,
    narrative:
      "Below spot magnet concentration attracts structural institutional buyer hedging.",
    tagText: "CONVICTION",
    shelf: "conviction",
    delta: 0.62,
    gamma: 0.021,
    vega: 0.13,
    theta: -0.92,
    volume: 18940,
    price: 11.2,
    bid: 11.1,
    ask: 11.3,
    t1: 15.6,
    p1: 39,
  },
  {
    id: "spy-510-c",
    ticker: "SPY",
    strike: 510,
    isCall: true,
    health: 92,
    expectedMove: "+34.8%",
    action: "ENTER" as const,
    narrative:
      "Slayer deep learning index detects massive localized volume sweep.",
    tagText: "CONVICTION",
    shelf: "conviction",
    delta: 0.58,
    gamma: 0.035,
    vega: 0.13,
    theta: -0.48,
    volume: 45100,
    price: 5.1,
    bid: 5.05,
    ask: 5.15,
    t1: 6.85,
    p1: 34,
  },

  // SHELF: IMPROVED / VELOCITY
  {
    id: "ndx-18300-c",
    ticker: "NDX",
    strike: 18300,
    isCall: true,
    health: 89,
    expectedMove: "+55.2%",
    action: "ENTER" as const,
    narrative:
      "Rapid jump in scoring index over the last 15 minutes. High expansion.",
    tagText: "VELOCITY",
    shelf: "improved",
    delta: 0.58,
    gamma: 0.018,
    vega: 0.19,
    theta: -1.15,
    volume: 6310,
    price: 14.2,
    bid: 14.05,
    ask: 14.35,
    t1: 22.01,
    p1: 55,
  },
  {
    id: "nvda-135-c",
    ticker: "NVDA",
    strike: 135,
    isCall: true,
    health: 88,
    expectedMove: "+32.4%",
    action: "ENTER" as const,
    narrative:
      "Dealer short blocks have dissolved, freeing up massive room overhead.",
    tagText: "VELOCITY",
    shelf: "improved",
    delta: 0.54,
    gamma: 0.043,
    vega: 0.16,
    theta: -0.58,
    volume: 29402,
    price: 3.8,
    bid: 3.75,
    ask: 3.85,
    t1: 5.05,
    p1: 32,
  },
  {
    id: "tsla-250-c",
    ticker: "TSLA",
    strike: 250,
    isCall: true,
    health: 87,
    expectedMove: "+28.5%",
    action: "ENTER" as const,
    narrative:
      "Score rating surges as dealers transition from negative gamma to neutral gamma.",
    tagText: "VELOCITY",
    shelf: "improved",
    delta: 0.51,
    gamma: 0.039,
    vega: 0.12,
    theta: -0.46,
    volume: 18920,
    price: 2.8,
    bid: 2.77,
    ask: 2.83,
    t1: 3.6,
    p1: 28,
  },
  {
    id: "meta-580-c",
    ticker: "META",
    strike: 580,
    isCall: true,
    health: 86,
    expectedMove: "+45.0%",
    action: "ENTER" as const,
    narrative:
      "Breakout momentum identified. Standard dispersion limit predicts vol expansion.",
    tagText: "VELOCITY",
    shelf: "improved",
    delta: 0.42,
    gamma: 0.019,
    vega: 0.14,
    theta: -0.84,
    volume: 9811,
    price: 4.8,
    bid: 4.7,
    ask: 4.9,
    t1: 6.95,
    p1: 45,
  },
  {
    id: "qqq-450-c",
    ticker: "QQQ",
    strike: 450,
    isCall: true,
    health: 85,
    expectedMove: "+26.8%",
    action: "ENTER" as const,
    narrative:
      "Derivative speed indices ticking straight up; fast buy feedback loop active.",
    tagText: "VELOCITY",
    shelf: "improved",
    delta: 0.46,
    gamma: 0.04,
    vega: 0.17,
    theta: -0.61,
    volume: 15400,
    price: 2.65,
    bid: 2.61,
    ask: 2.69,
    t1: 3.35,
    p1: 26,
  },
  {
    id: "spx-7640-c",
    ticker: "SPX",
    strike: 7640,
    isCall: true,
    health: 88,
    expectedMove: "+30.2%",
    action: "ENTER" as const,
    narrative:
      "Rapid acceleration in order flow profile matches strong buy trend.",
    tagText: "VELOCITY",
    shelf: "improved",
    delta: 0.52,
    gamma: 0.022,
    vega: 0.13,
    theta: -0.85,
    volume: 12401,
    price: 6.8,
    bid: 6.7,
    ask: 6.9,
    t1: 8.85,
    p1: 30,
  },

  // SHELF: MISPRICED / ARBITRAGE
  {
    id: "aapl-210-p",
    ticker: "AAPL",
    strike: 210,
    isCall: false,
    health: 85,
    expectedMove: "+24.1%",
    action: "HOLD" as const,
    narrative:
      "Valuation curve points to an extreme temporary discount on deep puts.",
    tagText: "MISPRICED",
    shelf: "mispriced",
    delta: -0.12,
    gamma: 0.008,
    vega: 0.06,
    theta: -0.15,
    volume: 5310,
    price: 0.45,
    bid: 0.43,
    ask: 0.47,
    t1: 0.55,
    p1: 22,
  },
  {
    id: "pltr-35-c",
    ticker: "PLTR",
    strike: 35,
    isCall: true,
    health: 83,
    expectedMove: "+18.5%",
    action: "HOLD" as const,
    narrative:
      "Priced exceptionally cheap relative to general spot move; heavy IV discount.",
    tagText: "MISPRICED",
    shelf: "mispriced",
    delta: 0.45,
    gamma: 0.02,
    vega: 0.14,
    theta: -0.83,
    volume: 8105,
    price: 5.1,
    bid: 5.0,
    ask: 5.2,
    t1: 6.05,
    p1: 18,
  },
  {
    id: "smci-45-p",
    ticker: "SMCI",
    strike: 45,
    isCall: false,
    health: 81,
    expectedMove: "+20.5%",
    action: "HOLD" as const,
    narrative:
      "Theoretical model price sits at $1.85, while active broker ask is $1.35.",
    tagText: "MISPRICED",
    shelf: "mispriced",
    delta: -0.38,
    gamma: 0.025,
    vega: 0.11,
    theta: -0.32,
    volume: 12502,
    price: 1.35,
    bid: 1.32,
    ask: 1.38,
    t1: 1.62,
    p1: 20,
  },
  {
    id: "spx-7590-p",
    ticker: "SPX",
    strike: 7590,
    isCall: false,
    health: 84,
    expectedMove: "+27.0%",
    action: "ENTER" as const,
    narrative:
      "Implied volatility suppression created a perfect risk-to-reward underpricing node.",
    tagText: "MISPRICED",
    shelf: "mispriced",
    delta: -0.41,
    gamma: 0.018,
    vega: 0.13,
    theta: -0.75,
    volume: 7500,
    price: 12.8,
    bid: 12.6,
    ask: 13.0,
    t1: 16.25,
    p1: 27,
  },
  {
    id: "qqq-442-p",
    ticker: "QQQ",
    strike: 442,
    isCall: false,
    health: 80,
    expectedMove: "+19.2%",
    action: "HOLD" as const,
    narrative:
      "Underpriced hedge option with high delta sensitivity relative to current spot.",
    tagText: "MISPRICED",
    shelf: "mispriced",
    delta: -0.39,
    gamma: 0.034,
    vega: 0.14,
    theta: -0.42,
    volume: 16210,
    price: 2.15,
    bid: 2.12,
    ask: 2.18,
    t1: 2.56,
    p1: 19,
  },
  {
    id: "ndx-18200-p",
    ticker: "NDX",
    strike: 18200,
    isCall: false,
    health: 82,
    expectedMove: "+22.4%",
    action: "HOLD" as const,
    narrative:
      "Strong theoretical offset detected. Arbitrage spread calculated at 14.5%.",
    tagText: "ARBITRAGE",
    shelf: "mispriced",
    delta: -0.44,
    gamma: 0.014,
    vega: 0.18,
    theta: -1.1,
    volume: 3840,
    price: 42.1,
    bid: 41.5,
    ask: 42.7,
    t1: 51.5,
    p1: 22,
  },

  // SHELF: INVALIDATION / BOUNDARIES
  {
    id: "spx-7610-p",
    ticker: "SPX",
    strike: 7610,
    isCall: false,
    health: 48,
    expectedMove: "-15.4%",
    action: "REDUCE" as const,
    narrative:
      "Slipped past main dealer GEX hedge floor. Tail risk exponentially flashing high.",
    tagText: "INVALIDATION",
    shelf: "invalidation",
    delta: -0.42,
    gamma: 0.021,
    vega: 0.13,
    theta: -0.85,
    volume: 15401,
    price: 18.5,
    bid: 18.3,
    ask: 18.7,
    t1: 15.65,
    p1: -15,
  },
  {
    id: "avgo-180-p",
    ticker: "AVGO",
    strike: 180,
    isCall: false,
    health: 51,
    expectedMove: "-10.2%",
    action: "SELL" as const,
    narrative:
      "Liquidity sweep void detected below current level. Immediate defensive alert.",
    tagText: "INVALIDATION",
    shelf: "invalidation",
    delta: -0.1,
    gamma: 0.005,
    vega: 0.05,
    theta: -0.12,
    volume: 24500,
    price: 0.35,
    bid: 0.33,
    ask: 0.37,
    t1: 0.31,
    p1: -10,
  },
  {
    id: "amzn-205-p",
    ticker: "AMZN",
    strike: 205,
    isCall: false,
    health: 41,
    expectedMove: "-24.0%",
    action: "SELL" as const,
    narrative:
      "Extreme threshold crossover boundary triggers automatic institutional liquidation.",
    tagText: "INVALIDATION",
    shelf: "invalidation",
    delta: -0.32,
    gamma: 0.016,
    vega: 0.12,
    theta: -0.8,
    volume: 11040,
    price: 8.5,
    bid: 8.35,
    ask: 8.65,
    t1: 6.45,
    p1: -24,
  },
  {
    id: "spy-502-p",
    ticker: "SPY",
    strike: 502,
    isCall: false,
    health: 45,
    expectedMove: "-18.5%",
    action: "SELL" as const,
    narrative:
      "Brushed beneath primary dealer put wall support. Hedging dynamics turned negative.",
    tagText: "INVALIDATION",
    shelf: "invalidation",
    delta: -0.28,
    gamma: 0.022,
    vega: 0.09,
    theta: -0.28,
    volume: 19105,
    price: 2.1,
    bid: 2.05,
    ask: 2.15,
    t1: 1.71,
    p1: -18,
  },
  {
    id: "qqq-438-p",
    ticker: "QQQ",
    strike: 438,
    isCall: false,
    health: 49,
    expectedMove: "-14.0%",
    action: "REDUCE" as const,
    narrative:
      "Unwinds beneath crucial volume-weighted index pivot. Support levels dissolve.",
    tagText: "INVALIDATION",
    shelf: "invalidation",
    delta: -0.31,
    gamma: 0.028,
    vega: 0.12,
    theta: -0.38,
    volume: 14210,
    price: 3.15,
    bid: 3.1,
    ask: 3.2,
    t1: 2.7,
    p1: -14,
  },
  {
    id: "ndx-18100-p",
    ticker: "NDX",
    strike: 18100,
    isCall: false,
    health: 38,
    expectedMove: "-32.5%",
    action: "SELL" as const,
    narrative:
      "System score degraded as gamma flip point triggers extreme margin sell hedging.",
    tagText: "INVALIDATION",
    shelf: "invalidation",
    delta: -0.36,
    gamma: 0.01,
    vega: 0.16,
    theta: -1.02,
    volume: 2901,
    price: 28.5,
    bid: 28.0,
    ask: 29.0,
    t1: 19.2,
    p1: -32,
  },

  // SHELF: WHALE SWEEPS
  {
    id: "spx-7700-c",
    ticker: "SPX",
    strike: 7700,
    isCall: true,
    health: 94,
    expectedMove: "+62.4%",
    action: "ENTER" as const,
    narrative:
      "Block institutional trades sweep SPX 7700 strike, representing $14.2M notional.",
    tagText: "WHALE",
    shelf: "whale",
    delta: 0.35,
    gamma: 0.018,
    vega: 0.15,
    theta: -0.78,
    volume: 62400,
    price: 2.45,
    bid: 2.4,
    ask: 2.5,
    t1: 3.98,
    p1: 62,
  },
  {
    id: "ndx-18500-c",
    ticker: "NDX",
    strike: 18500,
    isCall: true,
    health: 91,
    expectedMove: "+75.0%",
    action: "ENTER" as const,
    narrative:
      "Massive out-of-the-money block trade cluster. Aggressive bullish volatility positioning.",
    tagText: "WHALE",
    shelf: "whale",
    delta: 0.3,
    gamma: 0.01,
    vega: 0.17,
    theta: -1.08,
    volume: 11400,
    price: 8.9,
    bid: 8.7,
    ask: 9.1,
    t1: 15.55,
    p1: 75,
  },
  {
    id: "gme-30-c",
    ticker: "GME",
    strike: 30,
    isCall: true,
    health: 89,
    expectedMove: "+44.1%",
    action: "ENTER" as const,
    narrative:
      "Sweeps executed on Ask price consistently over the last 10 minutes. Bull run.",
    tagText: "WHALE",
    shelf: "whale",
    delta: 0.34,
    gamma: 0.031,
    vega: 0.11,
    theta: -0.4,
    volume: 92400,
    price: 1.15,
    bid: 1.12,
    ask: 1.18,
    t1: 1.65,
    p1: 44,
  },
  {
    id: "qqq-455-c",
    ticker: "QQQ",
    strike: 455,
    isCall: true,
    health: 88,
    expectedMove: "+38.5%",
    action: "ENTER" as const,
    narrative:
      "Multimillion institutional block sweep targeting the upper resistance channel wall.",
    tagText: "WHALE",
    shelf: "whale",
    delta: 0.32,
    gamma: 0.033,
    vega: 0.13,
    theta: -0.52,
    volume: 51200,
    price: 1.45,
    bid: 1.41,
    ask: 1.49,
    t1: 2.01,
    p1: 38,
  },
  {
    id: "spx-7500-p",
    ticker: "SPX",
    strike: 7500,
    isCall: false,
    health: 85,
    expectedMove: "+52.0%",
    action: "HOLD" as const,
    narrative:
      "Huge defensive protective put basket sweep ($22.4M notional hedge) detected.",
    tagText: "WHALE",
    shelf: "whale",
    delta: -0.19,
    gamma: 0.01,
    vega: 0.09,
    theta: -0.55,
    volume: 48900,
    price: 4.8,
    bid: 4.7,
    ask: 4.9,
    t1: 7.3,
    p1: 52,
  },
  {
    id: "ndx-17800-p",
    ticker: "NDX",
    strike: 17800,
    isCall: false,
    health: 83,
    expectedMove: "+48.5%",
    action: "HOLD" as const,
    narrative:
      "Significant tail protection sweep blocks are locking up hedge positions at put wall.",
    tagText: "WHALE",
    shelf: "whale",
    delta: -0.15,
    gamma: 0.008,
    vega: 0.12,
    theta: -0.78,
    volume: 8520,
    price: 12.4,
    bid: 12.1,
    ask: 12.7,
    t1: 18.4,
    p1: 48,
  },
];

const INITIAL_FEED_LOGS = [
  {
    timestamp: "01:34:25",
    ticker: "SPX",
    strike: 7620,
    type: "C",
    side: "Sweep",
    size: "280 cons",
    premium: "$151,200",
    tag: "BULLISH",
    action: "SWEPT @ ASK",
  },
  {
    timestamp: "01:34:10",
    ticker: "QQQ",
    strike: 448,
    type: "C",
    side: "Block",
    size: "1,200 cons",
    premium: "$504,000",
    tag: "BULLISH",
    action: "AT ASK",
  },
  {
    timestamp: "01:33:48",
    ticker: "NDX",
    strike: 18350,
    type: "C",
    side: "Block",
    size: "150 cons",
    premium: "$232,500",
    tag: "BULLISH",
    action: "ABOVE ASK",
  },
  {
    timestamp: "01:33:02",
    ticker: "SPY",
    strike: 508,
    type: "P",
    side: "Sweep",
    size: "2,500 cons",
    premium: "$337,500",
    tag: "BEARISH",
    action: "SWEPT @ ASK",
  },
  {
    timestamp: "01:31:55",
    ticker: "SPX",
    strike: 7700,
    type: "C",
    side: "Block",
    size: "3,000 cons",
    premium: "$735,000",
    tag: "BULLISH",
    action: "OFF-EXCHANGE",
  },
  {
    timestamp: "01:30:22",
    ticker: "NDX",
    strike: 17800,
    type: "P",
    side: "Sweep",
    size: "400 cons",
    premium: "$496,000",
    tag: "HEDGE",
    action: "SWEPT @ ASK",
  },
  {
    timestamp: "01:29:15",
    ticker: "SPY",
    strike: 515,
    type: "C",
    side: "Sweep",
    size: "1,800 cons",
    premium: "$576,000",
    tag: "BULLISH",
    action: "SWEPT @ ASK",
  },
  {
    timestamp: "01:28:40",
    ticker: "QQQ",
    strike: 455,
    type: "C",
    side: "Sweep",
    size: "2,400 cons",
    premium: "$348,000",
    tag: "BULLISH",
    action: "ABOVE ASK",
  },
];

interface MockState { contracts: any[]; feedLogs: any[]; startSimulation: () => void; }
export const useLiveMockStore = create<MockState>((set) => ({
  contracts: INITIAL_CONTRACTS,
  feedLogs: INITIAL_FEED_LOGS,
  startSimulation: () => {
    setInterval(() => {
        set(state => ({
            contracts: state.contracts.map(c => {
                const move = c.price * (Math.random() * 0.008 - 0.004);
                const newPrice = Math.max(0.01, c.price + move);
                return {
                    ...c,
                    price: newPrice,
                    bid: newPrice * 0.98,
                    ask: newPrice * 1.02,
                    health: Math.min(100, Math.max(0, c.health + (Math.random() > 0.5 ? 2 : -2))),
                    vega: Math.min(0.5, Math.max(0.01, c.vega + (Math.random() * 0.02 - 0.01))),
                };
            })
        }));
    }, 450);

    setInterval(() => {
        set(state => {
            const nextLog = { ...state.feedLogs[0] };
            const num = parseFloat(nextLog.premium.replace(/[^0-9.]/g, '')) * (1 + (Math.random() * 0.04 - 0.02));
            nextLog.premium = '$' + num.toLocaleString(undefined, { maximumFractionDigits: 0 });
            
            const timeParts = nextLog.timestamp.split(':');
            let h = parseInt(timeParts[0]);
            let m = parseInt(timeParts[1]);
            let s = parseInt(timeParts[2]) + 1;
            if (s >= 60) { s -= 60; m += 1; }
            if (m >= 60) { m -= 60; h += 1; }
            nextLog.timestamp = `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
            
            // Maybe randomly pick a ticker and side
            const pLogs = state.feedLogs;
            const randomLogTemplate = pLogs[Math.floor(Math.random() * pLogs.length)];
            nextLog.ticker = randomLogTemplate.ticker;
            nextLog.strike = randomLogTemplate.strike;
            nextLog.type = randomLogTemplate.type;
            nextLog.side = randomLogTemplate.side;
            nextLog.tag = randomLogTemplate.tag;
            
            return {
                feedLogs: [nextLog, ...state.feedLogs.slice(0, state.feedLogs.length - 1)]
            };
        });
    }, 250);
  }
}));

useLiveMockStore.getState().startSimulation();
